In [4]:
import numpy as np
random_matrix = np.random.random((3,3))
random_m2 = np.random.random((3,3))
result=np.zeros([3,3])
for i in range (len(random_matrix)):
    for j in range (len(random_m2[0])):
        for k in range (len(random_m2)):
              result[i][j] = random_matrix[i][k]*random_m2[k][j]
print ("1st Matrix:")
print (random_matrix)
print ("2nd Matrix:")
print (random_m2)
print ("Resultant Matrix:")
print (result)


1st Matrix:
[[0.88907294 0.56117615 0.10574699]
 [0.39091701 0.46684543 0.87010983]
 [0.95709565 0.38845983 0.41248253]]
2nd Matrix:
[[0.27112192 0.27354179 0.13527674]
 [0.28006415 0.60191994 0.49291673]
 [0.9309985  0.96638083 0.47914459]]
Resultant Matrix:
[[0.09845029 0.10219186 0.0506681 ]
 [0.81007095 0.84085746 0.41690842]
 [0.38402062 0.39861521 0.19763877]]
